### ISSUE TITLE
Cluster group suggestion

### ISSUE THREAD

**Issue by ramirovjr** [dprokscha/cputty#4]
Is it possible to have cluster groups?

Imagine for example that we have the setup:

2 servers running X services
2 other servers running Y services

And we would like to keep the connection with the 4 servers, but without having to remove cluster windows and adding the others, because some commands exist in a server, but no in another.

Shortcuts like Ctrl + Alt + PgUp + 1 (repeat for N windows on group 1)
Shortcuts like Ctrl + Alt + PgUp + 2 (repeat for N windows on group 2)

**Comment by dprokscha** [comment]
Better late then never :yum:

Check out [the latest release](https://github.com/dprokscha/cputty/releases) - I have added support for grouped clusters. You can find more infos in the project's README.
